title: "Draft, Analyze, and Present with Microsoft 365 Copilot"
author: "Asraf-JS"
github_repo: "https://github.com/Asraf-JS/draft-analyze-and-present-with-microsoft-365-copilot"

markdown: kramdown
encoding: utf-8
kramdown:
  syntax_highlighter_opts:
    disable: true
  input: GFM
  html_to_native: true

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.md"
    values:
      layout: "home"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
